In [1]:
import numpy as np

# Attributes

In [2]:
a = np.arange(0, 16).reshape((4, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
print("ndim     : ", a.ndim)
print("shape    : ", a.shape)
print("size     : ", a.size)
print("dtype    : ", a.dtype)

ndim     :  2
shape    :  (4, 4)
size     :  16
dtype    :  int64


# 1D Slicing

In [4]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[1:3]

array([1, 2])

In [8]:
a[1: -1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a[::2]

array([0, 2, 4, 6, 8])

In [10]:
a[1::2]

array([1, 3, 5, 7, 9])

In [11]:
a[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
a[-1:1:-2]

array([9, 7, 5, 3])

In [13]:
a[:1:-2] # for negative steps, default start index is -1

array([9, 7, 5, 3])

In [14]:
F = np.array([2, 1, 1, 2, 3, 5, 8])
F[::3]

array([2, 2, 8])

# 2D Slicing

In [15]:
a = np.arange(16)
a = a.reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
a[:, 1]

array([ 1,  5,  9, 13])

In [17]:
a[1, :]

array([4, 5, 6, 7])

In [18]:
a[1, ::2]

array([4, 6])

In [19]:
a[:, :-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [20]:
a[:-1, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a[:-1] # same as above. if no slice notation is provided, then : is default

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

One commonly needed routine is accessing single rows or columns of an array. This
can be done by combining indexing and slicing, using an empty slice marked by a
single colon (:):

In [22]:
a[:, 0] # first column of x2

array([ 0,  4,  8, 12])

In [23]:
a[0, :] # first row of x2

array([0, 1, 2, 3])

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [24]:
a[0] # equivalent to a[0, :]

array([0, 1, 2, 3])

# Fancy Indexing

In [25]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [26]:
# fancy indexing means you use an array as index
ind = [2, 3, 4]
a[ind]

array([2, 3, 4])

In [27]:
# shape of result reflects the shape of the index array 
# not the shape of the array being indexed
ind = np.array([[3, 2], [4, 1]])
a[ind]

array([[3, 2],
       [4, 1]])

# Boolean Indexing

In [28]:
a = np.arange(12).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
masked_indexes = a > 4
masked_indexes

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
a[masked_indexes] # returns a list of values at those indexes

array([ 5,  6,  7,  8,  9, 10, 11])

In [31]:
a[masked_indexes] = 55

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4, 55, 55, 55],
       [55, 55, 55, 55]])

# Array Splitting

In [33]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [34]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [36]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Array Combine

In [37]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [38]:
a

array([[1, 2],
       [3, 4]])

In [39]:
np.stack((a, b), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Products

In [41]:
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Hadamard product using the * operator
C = A * B
C

array([[ 5, 12],
       [21, 32]])

In [42]:
C = np.dot(A, B)
C

array([[19, 22],
       [43, 50]])

In [43]:
C = np.matmul(A, B)
C

array([[19, 22],
       [43, 50]])

In [44]:
A @ B

array([[19, 22],
       [43, 50]])

# Missing Values

In [45]:
a = np.array([np.nan, 5, 4, -3])
a.mean()

np.float64(nan)

In [46]:
a[0] = a[1:].mean()
a.mean()

np.float64(2.0)