This is based on this [blogpost](https://realpython.com/linear-regression-in-python/)

In [11]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [12]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [13]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [14]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [15]:
x_ = transformer.transform(x)

In [16]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [17]:
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [18]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [19]:
model = LinearRegression().fit(x_, y)

In [20]:
print(f"coefficient of determination: {model.score(x_, y)}")
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498563
intercept: 21.372321428571432
coefficients: [-1.32357143  0.02839286]


In [21]:
y_pred = model.predict(x_)

In [22]:
y_pred

array([15.46428571,  7.90714286,  6.02857143,  9.82857143, 19.30714286,
       34.46428571])